
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: comment
      authentication-database: test
      username: fooadmin
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 421421